apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: Chainguard
      prefix: cgr.dev
      api_url: https://cgr.dev
      credentials: pullsecret:argocd/ky-rafaels-pull-secret
      defaultns: library
      default: true