apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-image-updater.yaml

images:
- name: quay.io/argoprojlabs/argocd-image-updater:v0.15.2
  newName: cgr.dev/ky-rafaels.example.com/argocd-image-updater
  newTag: 0.15.2 