---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotation: 
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  destination:
    namespace: 
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'git@github.com:ky-rafaels/image-updater.git'
    path: 
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true