---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations: 
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager 
      targetRevision: v1.17.1
      helm:
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/k8s/cert-manager/custom-values.yaml
    - repoURL: https://github.com/ky-rafaels/image-updater.git
      targetRevision: main
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true