---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations: 
    argocd-image-updater.argoproj.io/image-list: controller=cgr.dev/ky-rafaels.example.com/cert-manager-controller, webhook=cgr.dev/ky-rafafels.example.com/cert-manager-webhook, cainjector=cgr.dev/ky-rafaels.example.com/cert-manager-cainjector
    argocd-image-updater.argoproj.io/cert-manager.update-strategy: digest
    argocd-image-updater.argoproj.io/controller.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/controller.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/webhook.helm.image-name: webhook.image.repository
    argocd-image-updater.argoproj.io/webhook.helm.image-tag: webhook.image.tag
    argocd-image-updater.argoproj.io/cainjector.helm.image-name: cainjector.image.repository
    argocd-image-updater.argoproj.io/cainjector.helm.image-tag: cainjector.image.tag
    argocd-image-updater.argoproj.io/git-repository: https://github.com/ky-rafaels/image-updater.git
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/git-branch: main
    # Optionally use git write back strategy
    # argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd-image-updater/git-creds
    # regexp below specifies version tagging in 0.0.0 format
    # argocd-image-updater.argoproj.io/myalias.allow-tags: regexp:^1\.[0-9]+\.[0-9]+$
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager 
      targetRevision: v1.17.1
      helm:
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/k8s/cert-manager/custom-values.yaml
    - repoURL: https://github.com/ky-rafaels/image-updater.git
      targetRevision: main
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true